version: '3.3'
services:
    arangodb:
        ports:
            - '8529:8529'
        environment:
            - ARANGO_ROOT_PASSWORD=trudne
        container_name: arango_ex
        image: 'arangodb/arangodb:3.9.1'
